# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [3]:
#Creating sample array
arr=np.arange(0,21)

In [4]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[9]

9

In [5]:
#Get values in a range
arr[1:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
#Setting a value with index range (Broadcasting)
arr[:]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [12]:
arr1=np.array([1,2,3])

In [14]:
arr1

array([1, 2, 3])

In [13]:
arr2=np.array([4,5,6])

In [15]:
arr2

array([4, 5, 6])

In [17]:
arr1-arr2

array([-3, -3, -3])

In [18]:
arr1*arr2

array([ 4, 10, 18])

In [19]:
# Filtering condition 

arr=np.array([1,2,1010,4,8,18,7])

In [20]:
np.where(arr>100) # where function outputs index location of condition

(array([2]),)

In [21]:
np.where(arr<100)

(array([0, 1, 3, 4, 5, 6]),)

In [22]:
# copy operation
arr=np.array([1,2,3,4,5])

In [23]:
arr[3:]=100

In [24]:
arr

array([  1,   2,   3, 100, 100])

In [25]:
arr1=arr # assigning the elements of arr to arr1 # backup

In [27]:
arr

array([  1,   2,   3, 100, 100])

In [26]:
arr1

array([  1,   2,   3, 100, 100])

In [28]:
arr1[3:]=500

In [29]:
arr1 # new array

array([  1,   2,   3, 500, 500])

In [30]:
arr

array([  1,   2,   3, 500, 500])

In [31]:
arr2=arr.copy()

In [32]:
arr

array([  1,   2,   3, 500, 500])

In [33]:
arr2

array([  1,   2,   3, 500, 500])

In [34]:
arr2[3:]=100

In [35]:
arr2

array([  1,   2,   3, 100, 100])

In [36]:
arr # rstored the property of backup.

array([  1,   2,   3, 500, 500])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [37]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [39]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [40]:
# Getting individual element value
arr_2d[1,0]

20

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [43]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [44]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [45]:
#Set up matrix
arr2d = np.zeros((10,10))

In [47]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
#Length of array
arr2d.shape


(10, 10)

In [48]:
no_of_rows=arr2d.shape[0]

In [49]:
no_of_rows

10

In [51]:
#Set up array

for i in range(no_of_rows):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [53]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [52]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [54]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [55]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

# Happy Learning!